local git = require("zdiff.git")
local git_repo = require("tests.helpers.git_repo")

describe("git adapter", function()
  it("returns git stderr for failed line commands", function()
    local repo = git_repo.create()
    local result = git.run_lines(repo, { "rev-parse", "--verify", "missing-ref" })

    assert.is_false(result.ok)
    assert.is_truthy(result.error:find("Needed a single revision", 1, true))
  end)

  it("reports invalid refs", function()
    local repo = git_repo.create()
    local result = git.ref_exists(repo, "missing-ref")

    assert.is_false(result.ok)
    assert.is_truthy(result.error)
  end)

  it("lists staged files before the first commit", function()
    local repo = git_repo.create()
    git_repo.write_file(repo .. "/new.txt", "one\n")
    git_repo.run(repo, { "add", "--", "new.txt" })

    local file = git_repo.find_file(git_repo.changed_files(repo), "new.txt")
    assert.is_not_nil(file)
    assert.equals("A", file.status)
    assert.equals(1, file.insertions)
    assert.equals(0, file.deletions)
  end)

  it("lists staged-only changes after a commit", function()
    local repo = git_repo.create()
    git_repo.write_file(repo .. "/tracked.txt", "one\n")
    git_repo.commit_all(repo, "baseline")
    git_repo.write_file(repo .. "/tracked.txt", "two\n")
    git_repo.run(repo, { "add", "--", "tracked.txt" })

    local file = git_repo.find_file(git_repo.changed_files(repo), "tracked.txt")
    assert.is_not_nil(file)
    assert.equals("M", file.status)
    assert.equals(1, file.insertions)
    assert.equals(1, file.deletions)
  end)

  it("parses NUL-delimited paths without Git quote escaping", function()
    local repo = git_repo.create()
    local path = "tabs\tand\ncafé.txt"
    git_repo.write_file(repo .. "/" .. path, "one\n")
    git_repo.commit_all(repo, "baseline")
    git_repo.write_file(repo .. "/" .. path, "two\n")

    local file = git_repo.find_file(git_repo.changed_files(repo), path)
    assert.is_not_nil(file)
    assert.equals("M", file.status)
    assert.equals(path, file.path)
    assert.equals(path, file.display_path)
    assert.equals(path, file.old_path)
    assert.equals(path, file.new_path)
    assert.equals(1, file.insertions)
    assert.equals(1, file.deletions)
  end)

  it("keeps old paths for deleted files", function()
    local repo = git_repo.create()
    git_repo.write_file(repo .. "/deleted.txt", "gone\n")
    git_repo.commit_all(repo, "baseline")
    git_repo.run(repo, { "rm", "--", "deleted.txt" })

    local file = git_repo.find_file(git_repo.changed_files(repo), "deleted.txt")
    assert.is_not_nil(file)
    assert.equals("D", file.status)
    assert.equals("deleted.txt", file.path)
    assert.equals("deleted.txt", file.old_path)
    assert.is_nil(file.new_path)
    assert.equals(0, file.insertions)
    assert.equals(1, file.deletions)
  end)

  it("keeps old and new paths for pure renames", function()
    local repo = git_repo.create()
    git_repo.write_file(repo .. "/old name.txt", "same\n")
    git_repo.commit_all(repo, "baseline")
    git_repo.run(repo, { "mv", "old name.txt", "new name.txt" })

    local file = git_repo.find_file(git_repo.changed_files(repo), "new name.txt")
    assert.is_not_nil(file)
    assert.equals("R", file.status)
    assert.equals("new name.txt", file.path)
    assert.equals("old name.txt", file.old_path)
    assert.equals("new name.txt", file.new_path)
    assert.equals("old name.txt -> new name.txt", file.display_path)
    assert.equals(0, file.insertions)
    assert.equals(0, file.deletions)
  end)
end)
